name: svf-build

# Triggers the workflow on push or pull request events
on: [push, pull_request]

# Customize the env variable
env:
  SVF_CTIR: 1 
  SVF_Z3: 1

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest]
    steps:
      # checkout the repo
      - uses: actions/checkout@v2
      # setup the environment 
      - name: env-setup
        run: |
          echo $RUNNER_OS
          if [ "$RUNNER_OS" = "Linux" ]; then sudo apt-get update       ; fi
          if [ "$RUNNER_OS" = "Linux" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test       ; fi
          if [ "$RUNNER_OS" = "Linux" ]; then sudo apt-get update       ; fi
          if [ "$RUNNER_OS" = "Linux" ]; then sudo apt-get install cmake gcc g++ nodejs doxygen graphviz; fi
          if [ "$RUNNER_OS" = "macOS" ]; then export SDKROOT="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk" ; fi
      # build-svf
      - name: build-svf
        run:
          git clone "https://github.com/SVF-tools/Test-Suite.git";
          ${{github.workspace}}/build.sh
      # run ctest
      - name: ctest
        working-directory: ${{github.workspace}}/Release-build
        run: 
          ctest -VV