#!/bin/bash
###############################
#
# This script is used to run cpu2000/cpu2006 benchmarks
#
# Set the cpu config file with following options:
# CC   = clang -std=gnu89 -D_GNU_SOURCE -c -emit-llvm
# CLD  = CURRENT_FILE_PATH (e.g. /home/ysui/cpu2006/config/msc_cld)
#
##############################


LLVM_OBJROOT=/home/ysui/llvm-3.3/llvm-3.3.dbg
LLVM_BINROOT=$LLVM_OBJROOT/Debug+Asserts/bin
LLVM_LD=$LLVM_BINROOT/llvm-ld
LLVM_LINK=$LLVM_BINROOT/llvm-link

PTA_ROOT=/home/ysui/pta
WPA=$PTA_ROOT/Debug+Asserts/bin/wpa
WPAFLAG="-ander"



eval prog_name=\${$#}


# strip arguments llvm-ld doesn't understand
python << END
args = []
for arg in '$@'.split()[:-1]:
    if arg[:2] in ('-g', '-W', '-O', '-D', '-f'):
        continue
    args.append(arg)
open('link-args.txt', 'w').write(' '.join(args))
END


########linkage##########
sed -i 's/-lm//' link-args.txt
$LLVM_LINK `cat link-args.txt` $prog_name.orig
$WPA $WPAFLAG $prog_name.orig
$LLVM_BINROOT/llc -filetype=obj $prog_name.orig.wpa.bc -o $prog_name.orig.wpa.o
$LLVM_BINROOT/clang $prog_name.orig.wpa.o -o $prog_name -lm -lcrypt -lpthread ##put the linked *.a library here

#$LLVM_BINROOT/llc -O0 $prog_name.orig.bc -o $prog_name.s
#$LLVM_BINROOT/clang++ $prog_name.s -o $prog_name -lm

#gcc -o $prog_name -O0 $prog_name.orig.wpa.o 
#llc -filetype=obj $prog_name.orig
#gcc -o $prog_name -O0 $prog_name.orig.o ##put the linked *.a library here
